### ISSUE TITLE
Implementation help 

### ISSUE THREAD

**Issue by kianmeng-aft** [Polvista/ngtools-webpack-keep-decorators#1]
Hi,
Where do i change the config from https://github.com/ngrx/example-app ?

**Comment by Polvista** [comment]
Hey, unfortunately nowhere, since it doesn't use webpack to perform AOT compilation. 
This project doesn't solve internal angular-cli problem with custom decorators, it only helps if you use webpack + @ngtools/webpack instead of angular-cli.
